FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose Express port
EXPOSE 5000

# Start Express server
CMD ["node", "server.js"]
